### ISSUE TITLE
BUG: 海外机器无法下载国内平台的歌曲

### ISSUE THREAD

**Issue by docase** [foamzou/media-get#10]
### 酷我
>./media-get -u "https://www.kuwo.cn/play_detail/236967605" - t audio

panic: invalid character 'æ' looking for beginning of value

goroutine 1 [running]:
main.main()
        ./main.go:24 +0xab

### QQ音乐
 >.\media-get  -u "http://y.qq.com/n/ryqq/songDetail/0021bATQ1TadVT" - t audio

panic: can not get song url

goroutine 1 [running]:
main.main()
        ./main.go:24 +0xab

### 抖音 bilibili正常

**Comment by foamzou** [comment]
国内平台大多只允许国内 IP 访问。你的大概率是海外机器？

参考这个 PR，计划添加 proxy。如果有国内代理的话，到时候 feature launch 之后可以配置
https://github.com/foamzou/media-get/pull/8#issuecomment-1227413963

**Comment by mar-heaven** [comment]
> 国内平台大多只允许国内 IP 访问。你的大概率是海外机器？
> 
> 参考这个 PR，计划添加 proxy。如果有国内代理的话，到时候 feature launch 之后可以配置 [#8 (comment)](https://github.com/foamzou/media-get/pull/8#issuecomment-1227413963)

feature国庆完成吧~

**Comment by foamzou** [comment]
> > 国内平台大多只允许国内 IP 访问。你的大概率是海外机器？
> > 参考这个 PR，计划添加 proxy。如果有国内代理的话，到时候 feature launch 之后可以配置 [#8 (comment)](https://github.com/foamzou/media-get/pull/8#issuecomment-1227413963)
> 
> 周末出去浪了，feature放国庆实现。

Thx bro, just take your time.
