### ISSUE TITLE
Windows 平台，歌曲 Title 中包含文件名中不支持的字符（如半角冒号）时，歌曲下载后无法保存到本地

### ISSUE THREAD

**Issue by kamelija** [foamzou/media-get#11]
请问是否可以进行优化，将文件名中不支持的字符替换为空格或下划线等符号，以便可以正常保存。谢谢。

**Comment by foamzou** [comment]
https://github.com/foamzou/media-get/commit/eced5db7c045dd6172ea0998c1aae8ed37568ff4
