### ISSUE TITLE
Downloaded the latest release. What's next?

### ISSUE THREAD

**Issue by Qlub53** [foamzou/media-get#15]
Downloaded the latest `media-get-0.2.10-darwin-arm64` from "[Releases](https://github.com/foamzou/media-get/blob/main/README_en.md#download--update-the-tool)".

Now how do I run it?

Apparently `chmod +x media-get-0.2.10-darwin-arm64 && sh media-get-0.2.10-darwin-arm64` didn't help.

**Comment by foamzou** [comment]
This is binary. You can't execute it with `sh`. Just `./media-get-0.2.10-darwin-arm64`

BTW. Please rebuild the binary if you meet `segmentation fault` because I use upx to compress  the binary but the macOS 13 is not compatible.
@Qlub53

**Comment by Qlub53** [comment]
@foamzou thanks for your insights!
So I did the `chmod +x` part right, correct?

Any plans to support macOS 13?

**Comment by foamzou** [comment]
@Qlub53 
Sure, `chmod +x` is fine.

I will update the release when I am free. Maybe before 15th, Aug. 

You can build it with the source code as well.

**Comment by Qlub53** [comment]
Not an expert in C and its tech stack, though.

You said that it is `upx` causing  incompatibility with macOS 13. Is it a limitation of `upx` itself?

**Comment by foamzou** [comment]
upx will support the macOS 13 soon. I checked it was arranged to the roadmap and will release within 2 months.

**Comment by foamzou** [comment]
UPX does not support the latest macos. Do not compress for the binary before the upx done.
